Repository googleapis/google-cloud-python, pull requests merged in 2018-04, with the labels that each got.

#5125 BigQuery: Moves all Table property conversion logic into properties
  bigquery/google/cloud/bigquery/client.py
  bigquery/google/cloud/bigquery/table.py
  bigquery/tests/unit/test_client.py
  bigquery/tests/unit/test_table.py
Labels: api: bigquery, cla: yes

#5136 Release pubsub 0.33.1
  pubsub/CHANGELOG.md
  pubsub/setup.py
Labels: cla: yes

#5139 Add C++ to the list of languages on the index of the github.io page
  _landing-page-static/images/icon-lang-cpp.svg
  index.html
Labels: cla: yes

#5127 Vision v1p2beta1: PDF/TIFF OCR
  docs/vision/gapic/v1p2beta1/api.rst
  docs/vision/gapic/v1p2beta1/types.rst
  docs/vision/index.rst
  vision/google/cloud/vision_v1p2beta1/gapic/image_annotator_client.py
  vision/google/cloud/vision_v1p2beta1/proto/geometry_pb2.py
  vision/google/cloud/vision_v1p2beta1/proto/image_annotator_pb2.py
  vision/google/cloud/vision_v1p2beta1/proto/image_annotator_pb2_grpc.py
  vision/google/cloud/vision_v1p2beta1/proto/text_annotation_pb2.py
  vision/google/cloud/vision_v1p2beta1/proto/web_detection_pb2.py
  vision/tests/unit/gapic/v1p2beta1/test_image_annotator_client_v1p2beta1.py
Labels: cla: yes

#5146 Release vision 0.31.0
  vision/CHANGELOG.md
  vision/setup.py
Labels: cla: yes

#5147 Release bigquery 0.32.0
  bigquery/CHANGELOG.md
  bigquery/setup.py
Labels: cla: yes

#4819 Fix variable nanosecond timestamp update_time from response
  runtimeconfig/google/cloud/runtimeconfig/variable.py
  runtimeconfig/tests/unit/test_config.py
Labels: api: runtime config, cla: yes

#5150 RuntimeConfig: tests with microseconds and nanoseconds
  runtimeconfig/tests/unit/test_variable.py
Labels: api: runtime config, cla: yes

#5155 Remove DLP Client Version V2Beta1
  dlp/README.rst
  dlp/docs/gapic/v2beta1/api.rst
  dlp/docs/gapic/v2beta1/types.rst
  dlp/docs/index.rst
  dlp/google/cloud/dlp_v2beta1/__init__.py
  dlp/google/cloud/dlp_v2beta1/gapic/__init__.py
  dlp/google/cloud/dlp_v2beta1/gapic/dlp_service_client.py
  dlp/google/cloud/dlp_v2beta1/gapic/dlp_service_client_config.py
  dlp/google/cloud/dlp_v2beta1/gapic/enums.py
  dlp/google/cloud/dlp_v2beta1/proto/__init__.py
  dlp/google/cloud/dlp_v2beta1/proto/dlp_pb2.py
  dlp/google/cloud/dlp_v2beta1/proto/dlp_pb2_grpc.py
  dlp/google/cloud/dlp_v2beta1/proto/storage_pb2.py
  dlp/google/cloud/dlp_v2beta1/proto/storage_pb2_grpc.py
  dlp/google/cloud/dlp_v2beta1/types.py
  dlp/nox.py
  dlp/tests/system/gapic/v2beta1/test_system_dlp_service_v2beta1.py
  dlp/tests/unit/gapic/v2beta1/test_dlp_service_client_v2beta1.py
Labels: cla: yes

#5123 Audio Logging and Recognition Metadata.
  docs/speech/gapic/v1p1beta1/api.rst
  docs/speech/gapic/v1p1beta1/types.rst
  speech/google/cloud/speech_v1p1beta1/gapic/enums.py
  speech/google/cloud/speech_v1p1beta1/gapic/speech_client.py
  speech/google/cloud/speech_v1p1beta1/proto/cloud_speech_pb2.py
  speech/google/cloud/speech_v1p1beta1/proto/cloud_speech_pb2_grpc.py
Labels: cla: yes

#5160 Release dlp 0.4.0
  dlp/CHANGELOG.md
  dlp/setup.py
  dlp/tests/system/gapic/v2/test_system_dlp_service_v2.py
Labels: cla: yes

#5165 Generate videointelligence v1p1beta1
  videointelligence/google/cloud/videointelligence_v1p1beta1/gapic/enums.py
  videointelligence/google/cloud/videointelligence_v1p1beta1/gapic/video_intelligence_service_client.py
  videointelligence/google/cloud/videointelligence_v1p1beta1/proto/video_intelligence_pb2.py
  videointelligence/google/cloud/videointelligence_v1p1beta1/proto/video_intelligence_pb2_grpc.py
Labels: cla: yes

#5167 Release videointelligence 1.2.0
  videointelligence/CHANGELOG.md
  videointelligence/setup.py
Labels: cla: yes

#5166 Release speech 0.33.0
  speech/CHANGELOG.md
  speech/setup.py
Labels: cla: yes

#4851 Implement `MergeOption` as an option
  firestore/google/cloud/firestore.py
  firestore/google/cloud/firestore_v1beta1/__init__.py
  firestore/google/cloud/firestore_v1beta1/_helpers.py
  firestore/google/cloud/firestore_v1beta1/batch.py
  firestore/google/cloud/firestore_v1beta1/client.py
  firestore/google/cloud/firestore_v1beta1/document.py
  firestore/tests/system.py
  firestore/tests/unit/test__helpers.py
  firestore/tests/unit/test_batch.py
  firestore/tests/unit/test_client.py
  firestore/tests/unit/test_cross_language.py
  firestore/tests/unit/test_document.py
Labels: api: firestore, cla: yes, type: feature request

#5149 Firestore: __add__ function for FieldPaths
  firestore/google/cloud/firestore_v1beta1/_helpers.py
  firestore/tests/unit/test__helpers.py
Labels: api: firestore, cla: yes, type: cleanup

#5174 Fix snippets showing use of 'error_reporting.HTTPContext'.
  docs/error-reporting/usage.rst
Labels: api: error reporting, cla: yes, documentation

#5181 Replace link to 404 object IAM docs with a note on limited utility.
  storage/google/cloud/storage/blob.py
Labels: api: storage, cla: yes, documentation

#5182 BigQuery: Remove deprecated Client methods
  bigquery/google/cloud/bigquery/client.py
  bigquery/tests/unit/test_client.py
Labels: api: bigquery, cla: yes

#5184 Fix lint errors introduced in #5081.
  storage/google/cloud/storage/blob.py
  storage/google/cloud/storage/client.py
  storage/tests/unit/test_blob.py
Labels: api: storage, cla: yes, type: cleanup

#5185 Release bigquery 1.0.0
  bigquery/CHANGELOG.md
  bigquery/setup.py
Labels: cla: yes

#4785 Update monitoring gapic client, re-integrate helpers
  docs/monitoring/client.rst
  docs/monitoring/enums.rst
  docs/monitoring/group.rst
  docs/monitoring/label.rst
  docs/monitoring/metric.rst
  docs/monitoring/resource.rst
  docs/monitoring/timeseries.rst
  docs/monitoring/types.rst
  docs/monitoring/usage.rst
  monitoring/google/cloud/monitoring/__init__.py
  monitoring/google/cloud/monitoring/_dataframe.py
  monitoring/google/cloud/monitoring/query.py
  monitoring/google/cloud/monitoring_v3/proto/common_pb2.py
  monitoring/tests/unit/test__dataframe.py
  monitoring/tests/unit/test_query.py
Labels: api: monitoring, cla: yes, type: process

#5195 BigQuery: Samples update and region tag standardization
  bigquery/nox.py
  bigquery/tests/data/people.csv
  docs/bigquery/snippets.py
  docs/bigquery/usage.rst
Labels: api: bigquery, cla: yes, documentation

#5199 BigQuery: Adds samples from python-docs-samples
  docs/bigquery/snippets.py
  docs/bigquery/usage.rst
Labels: api: bigquery, cla: yes, documentation

#5189 Add bi-directional stream consumption helpers.
  pubsub/google/cloud/pubsub_v1/subscriber/_protocol/__init__.py
  pubsub/google/cloud/pubsub_v1/subscriber/_protocol/bidi.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_bidi.py
Labels: cla: yes

#5202 Don't suppress 'dots' output for snippets tests.
  bigquery/nox.py
Labels: api: bigquery, automerge, cla: yes, flaky, testing

#5201 Add subscriber dispatcher
  pubsub/google/cloud/pubsub_v1/subscriber/_consumer.py
  pubsub/google/cloud/pubsub_v1/subscriber/_protocol/dispatcher.py
  pubsub/google/cloud/pubsub_v1/subscriber/_protocol/helper_threads.py
  pubsub/google/cloud/pubsub_v1/subscriber/_protocol/requests.py
  pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py
  pubsub/google/cloud/pubsub_v1/subscriber/subscriber.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_consumer.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_dispatcher.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_helper_threads.py
Labels: cla: yes

#5187 Allow uploading files larger than 2GB by using Resumable Media Requests
  storage/google/cloud/storage/blob.py
  storage/tests/unit/test_blob.py
Labels: cla: yes

#5206 Release bigquery 1.0.1
  bigquery/CHANGELOG.md
  bigquery/setup.py
Labels: cla: yes

#5207 Release api_core 1.1.1
  api_core/CHANGELOG.md
  api_core/setup.py
Labels: cla: yes

#5208 Release bigquery 1.1.0
  bigquery/CHANGELOG.md
  bigquery/setup.py
Labels: api: bigquery, cla: yes, packaging, type: process

#5209 BigQuery: limit list_jobs sample to 10 most recent jobs
  docs/bigquery/snippets.py
Labels: cla: yes

#5211 BigQuery: Fix typo in Encoding.ISO_8859_1 enum value
  bigquery/google/cloud/bigquery/job.py
Labels: cla: yes

#5214 Fix issues with narrow screens #5213
  _landing-page-static/css/main.css
Labels: cla: yes

#5217 BigQuery: Add optional project parameter to `list_datasets` and `list_jobs`
  bigquery/google/cloud/bigquery/client.py
  bigquery/tests/system.py
  bigquery/tests/unit/test_client.py
Labels: api: bigquery, cla: yes

#5215 Fix broken pandas based tests
  monitoring/google/cloud/monitoring_v3/__init__.py
  monitoring/google/cloud/monitoring_v3/_dataframe.py
  monitoring/google/cloud/monitoring_v3/proto/common_pb2.py
  monitoring/tests/unit/test__dataframe.py
  monitoring/tests/unit/test_query.py
Labels: cla: yes

#5227 add gemfile to gh-pages branch
  Gemfile
Labels: cla: yes

#5228 Remove nojekyll file that was stopping jekyll builds
  .nojekyll
  Gemfile.lock
  _config.yml
Labels: cla: yes

#5229 Rename histogram module
  pubsub/google/cloud/pubsub_v1/subscriber/_protocol/histogram.py
  pubsub/google/cloud/pubsub_v1/subscriber/policy/base.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_histogram.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_leaser.py
Labels: cla: yes

#5226 Release monitoring 0.29.0
  monitoring/CHANGELOG.md
  monitoring/setup.py
Labels: cla: yes

#5230 Add scheduler
  pubsub/google/cloud/pubsub_v1/subscriber/scheduler.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_scheduler.py
Labels: cla: yes

#5231 BigQuery: Reduces repetition in load samples
  docs/bigquery/snippets.py
  docs/bigquery/usage.rst
Labels: api: bigquery, cla: yes

#5235 Regenerate speech v1p1beta1
  speech/LICENSE
  speech/MANIFEST.in
  speech/google/__init__.py
  speech/google/cloud/__init__.py
  speech/google/cloud/speech_v1p1beta1/gapic/enums.py
  speech/google/cloud/speech_v1p1beta1/proto/cloud_speech_pb2.py
Labels: cla: yes

#5236 Release speech 0.34.0
  speech/CHANGELOG.md
  speech/setup.py
Labels: api: speech, cla: yes, packaging

#5243 remove unnecessary gh-pages build
  test_utils/scripts/update_docs.sh
Labels: cla: yes

#5221 Add support for blob-level KMS encryption keys
  storage/google/cloud/storage/blob.py
  storage/tests/unit/test_blob.py
Labels: api: storage, automerge, cla: yes, type: feature request

#5222 Add 'Bucket.default_kms_encryption_key' property.
  storage/google/cloud/storage/bucket.py
  storage/tests/unit/test_bucket.py
Labels: api: storage, automerge, cla: yes, type: feature request

#5245 Fix docstring for 'ExtractJob.destination_uri_file_counts'.
  bigquery/google/cloud/bigquery/job.py
  bigquery/tests/system.py
  bigquery/tests/unit/test_job.py
Labels: api: bigquery, cla: yes, documentation, type: bug

#5237 Add streaming pull manager and integrate new subscriber logic
  pubsub/google/cloud/pubsub_v1/subscriber/_protocol/bidi.py
  pubsub/google/cloud/pubsub_v1/subscriber/_protocol/dispatcher.py
  pubsub/google/cloud/pubsub_v1/subscriber/_protocol/leaser.py
  pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
  pubsub/google/cloud/pubsub_v1/subscriber/client.py
  pubsub/google/cloud/pubsub_v1/subscriber/futures.py
  pubsub/google/cloud/pubsub_v1/subscriber/message.py
  pubsub/google/cloud/pubsub_v1/subscriber/policy/base.py
  pubsub/google/cloud/pubsub_v1/subscriber/subscriber.py
  pubsub/tests/system.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_dispatcher.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_futures_subscriber.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_leaser.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_message.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_subscriber_client.py
Labels: api: pubsub, cla: yes

#5246 Generate DLP v2
  dlp/google/cloud/dlp_v2/gapic/dlp_service_client.py
  dlp/google/cloud/dlp_v2/gapic/enums.py
  dlp/google/cloud/dlp_v2/proto/dlp_pb2.py
  dlp/google/cloud/dlp_v2/proto/dlp_pb2_grpc.py
  dlp/google/cloud/dlp_v2/proto/storage_pb2.py
Labels: cla: yes

#5248 Lower the flow control defaults, remove psutil dependency
  pubsub/google/cloud/pubsub_v1/subscriber/client.py
  pubsub/google/cloud/pubsub_v1/types.py
  pubsub/setup.py
Labels: cla: yes

#5247 Plug leaky sink in logging systests.
  logging/tests/system/test_system.py
Labels: api: logging, automerge, cla: yes, flaky, testing

#5249 Expose 'Blob.kms_key_name' as read-only property
  storage/google/cloud/storage/blob.py
  storage/tests/unit/test_blob.py
Labels: api: storage, cla: yes, type: feature request

#5255 BigQuery: add from_string factory methods to Dataset and Table
  bigquery/google/cloud/bigquery/dataset.py
  bigquery/google/cloud/bigquery/table.py
  bigquery/tests/unit/test_dataset.py
  bigquery/tests/unit/test_table.py
Labels: cla: yes

#5256 Fix race condition in bidi.BackgroundConsumer
  pubsub/google/cloud/pubsub_v1/subscriber/_protocol/bidi.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_bidi.py
Labels: cla: yes

#5258 Release pubsub 0.34.0
  pubsub/CHANGELOG.md
  pubsub/setup.py
Labels: cla: yes

#5263 Add example showing explicit unicode for text values in entities.
  datastore/google/cloud/datastore/__init__.py
Labels: api: datastore, cla: yes, documentation

#5265 Update setuptools, wheel, and twine before building packages
  test_utils/scripts/circleci/twine_upload.sh
Labels: cla: yes

#5264 Drop systest dependency expansion for bigquery/storage.
  test_utils/scripts/get_target_packages.py
Labels: cla: yes, testing, type: process

#5266 Update setup.py to use recommended method for python-verson specific dependencies
  language/setup.py
Labels: cla: yes

#5271 Release language 1.0.2
  language/CHANGELOG.md
  language/setup.py
Labels: cla: yes

#5270 Release vision 0.31.1
  vision/CHANGELOG.md
  vision/setup.py
Labels: cla: yes

#5272 Remove link to `usage` on index of monitoring
  monitoring/docs/index.rst
Labels: cla: yes
