Repository googleapis/google-cloud-python, pull requests merged in 2018-05, with the labels that each got.

#5279 Wire up scheduler argument for subscribe()
  pubsub/google/cloud/pubsub_v1/subscriber/client.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_subscriber_client.py
Labels: cla: yes

#5280 Remove unused var (flake8 warning)
  storage/google/cloud/storage/blob.py
Labels: cla: yes

#5277 Update docstring to reflect correct units
  storage/google/cloud/storage/blob.py
  storage/google/cloud/storage/bucket.py
Labels: cla: yes

#5278 Generate websecurity v1alpha
  websecurityscanner/LICENSE
  websecurityscanner/MANIFEST.in
  websecurityscanner/README.rst
  websecurityscanner/docs/conf.py
  websecurityscanner/docs/gapic/v1alpha/api.rst
  websecurityscanner/docs/gapic/v1alpha/types.rst
  websecurityscanner/docs/index.rst
  websecurityscanner/google/__init__.py
  websecurityscanner/google/cloud/__init__.py
  websecurityscanner/google/cloud/websecurityscanner.py
  websecurityscanner/google/cloud/websecurityscanner_v1alpha/__init__.py
  websecurityscanner/google/cloud/websecurityscanner_v1alpha/gapic/__init__.py
  websecurityscanner/google/cloud/websecurityscanner_v1alpha/gapic/enums.py
  websecurityscanner/google/cloud/websecurityscanner_v1alpha/gapic/web_security_scanner_client.py
  websecurityscanner/google/cloud/websecurityscanner_v1alpha/gapic/web_security_scanner_client_config.py
  websecurityscanner/google/cloud/websecurityscanner_v1alpha/proto/__init__.py
  websecurityscanner/google/cloud/websecurityscanner_v1alpha/proto/crawled_url_pb2.py
  websecurityscanner/google/cloud/websecurityscanner_v1alpha/proto/crawled_url_pb2_grpc.py
  websecurityscanner/google/cloud/websecurityscanner_v1alpha/proto/finding_addon_pb2.py
  websecurityscanner/google/cloud/websecurityscanner_v1alpha/proto/finding_addon_pb2_grpc.py
  websecurityscanner/google/cloud/websecurityscanner_v1alpha/proto/finding_pb2.py
  websecurityscanner/google/cloud/websecurityscanner_v1alpha/proto/finding_pb2_grpc.py
  websecurityscanner/google/cloud/websecurityscanner_v1alpha/proto/finding_type_stats_pb2.py
  websecurityscanner/google/cloud/websecurityscanner_v1alpha/proto/finding_type_stats_pb2_grpc.py
  websecurityscanner/google/cloud/websecurityscanner_v1alpha/proto/scan_config_pb2.py
  websecurityscanner/google/cloud/websecurityscanner_v1alpha/proto/scan_config_pb2_grpc.py
  websecurityscanner/google/cloud/websecurityscanner_v1alpha/proto/scan_run_pb2.py
  websecurityscanner/google/cloud/websecurityscanner_v1alpha/proto/scan_run_pb2_grpc.py
  websecurityscanner/google/cloud/websecurityscanner_v1alpha/proto/web_security_scanner_pb2.py
  websecurityscanner/google/cloud/websecurityscanner_v1alpha/proto/web_security_scanner_pb2_grpc.py
  websecurityscanner/google/cloud/websecurityscanner_v1alpha/types.py
  websecurityscanner/nox.py
  websecurityscanner/setup.cfg
  websecurityscanner/setup.py
  websecurityscanner/tests/unit/gapic/v1alpha/test_web_security_scanner_client_v1alpha.py
Labels: cla: yes

#5285 Release websecurityscanner 0.1.0
  websecurityscanner/CHANGELOG.md
Labels: cla: yes

#5267 BigQuery: Column based time partitioning
  bigquery/google/cloud/bigquery/__init__.py
  bigquery/google/cloud/bigquery/job.py
  bigquery/google/cloud/bigquery/table.py
  bigquery/tests/unit/test_client.py
  bigquery/tests/unit/test_job.py
  bigquery/tests/unit/test_table.py
  docs/bigquery/snippets.py
Labels: api: bigquery, cla: yes

#5286 Add dot files for websecurityscanner
  websecurityscanner/.coveragerc
  websecurityscanner/.flake8
  websecurityscanner/CHANGELOG.md
Labels: cla: yes

#5273 BigQuery: switch list_partitions helper to a direct metatable read
  bigquery/google/cloud/bigquery/client.py
  bigquery/tests/system.py
  bigquery/tests/unit/test_client.py
Labels: cla: yes

#5288 spanner fixes to enable 3.7 #5282
  .circleci/config.yml
  spanner/google/cloud/spanner_v1/streamed.py
  spanner/nox.py
Labels: cla: yes

#5289 BigQuery: Standardize docstrings for constants
  bigquery/google/cloud/bigquery/job.py
Labels: api: bigquery, cla: yes, documentation

#5295 Add Test runs for Python 3.7 and remove 3.4
  api_core/nox.py
  bigquery/nox.py
  bigquery_datatransfer/nox.py
  bigtable/nox.py
  container/nox.py
  core/nox.py
  dataproc/nox.py
  datastore/nox.py
  dlp/nox.py
  dns/nox.py
  error_reporting/nox.py
  firestore/nox.py
  language/nox.py
  logging/nox.py
  monitoring/nox.py
  oslogin/nox.py
  pubsub/google/cloud/pubsub_v1/subscriber/scheduler.py
  pubsub/nox.py
  resource_manager/nox.py
  runtimeconfig/nox.py
  speech/nox.py
  storage/nox.py
  texttospeech/nox.py
  trace/nox.py
  translate/nox.py
  videointelligence/nox.py
  vision/nox.py
  websecurityscanner/nox.py
Labels: cla: yes

#5297 Release bigquery 1.2.0
  bigquery/CHANGELOG.md
  bigquery/setup.py
Labels: cla: yes

#5299 Release storage 1.9.0
  storage/CHANGELOG.md
  storage/setup.py
Labels: cla: yes

#5309 Redis generated
  redis/.coveragerc
  redis/.flake8
  redis/LICENSE
  redis/MANIFEST.in
  redis/README.rst
  redis/docs/conf.py
  redis/docs/gapic/v1beta1/api.rst
  redis/docs/gapic/v1beta1/types.rst
  redis/docs/index.rst
  redis/google/__init__.py
  redis/google/cloud/__init__.py
  redis/google/cloud/redis.py
  redis/google/cloud/redis_v1beta1/__init__.py
  redis/google/cloud/redis_v1beta1/gapic/__init__.py
  redis/google/cloud/redis_v1beta1/gapic/cloud_redis_client.py
  redis/google/cloud/redis_v1beta1/gapic/cloud_redis_client_config.py
  redis/google/cloud/redis_v1beta1/gapic/enums.py
  redis/google/cloud/redis_v1beta1/proto/__init__.py
  redis/google/cloud/redis_v1beta1/proto/cloud_redis_pb2.py
  redis/google/cloud/redis_v1beta1/proto/cloud_redis_pb2_grpc.py
  redis/google/cloud/redis_v1beta1/types.py
  redis/nox.py
  redis/setup.cfg
  redis/setup.py
  redis/tests/unit/gapic/v1beta1/test_cloud_redis_client_v1beta1.py
Labels: api:redis, cla: yes

#5310 Release redis 0.1.0
  redis/CHANGELOG.md
Labels: cla: yes

#5259 Storage: add support for KMS keys
  storage/google/cloud/storage/blob.py
  storage/google/cloud/storage/bucket.py
  storage/tests/system.py
  storage/tests/unit/test_blob.py
  storage/tests/unit/test_bucket.py
Labels: api: storage, cla: yes, do not merge, type: feature request

#5312 Add timeline and top-level slot-millis to query statistics.
  bigquery/google/cloud/bigquery/job.py
  bigquery/tests/system.py
  bigquery/tests/unit/test_job.py
Labels: cla: yes

#5319 BigQuery: improve system test performance
  bigquery/tests/system.py
Labels: cla: yes

#5304 Grpcio pre system tests
  bigquery/nox.py
  bigquery_datatransfer/nox.py
  bigtable/nox.py
  container/nox.py
  dataproc/nox.py
  datastore/google/cloud/datastore/__init__.py
  datastore/nox.py
  dlp/nox.py
  error_reporting/nox.py
  firestore/nox.py
  language/nox.py
  logging/nox.py
  monitoring/nox.py
  pubsub/nox.py
  spanner/nox.py
  speech/nox.py
  storage/nox.py
  translate/nox.py
  vision/nox.py
Labels: api: core, cla: yes, testing

#5302 BigTable: Modify system test for new GAPIC code
  bigtable/google/cloud/bigtable/client.py
  bigtable/google/cloud/bigtable/cluster.py
  bigtable/google/cloud/bigtable/instance.py
  bigtable/tests/system.py
  bigtable/tests/unit/_testing.py
  bigtable/tests/unit/test_client.py
  bigtable/tests/unit/test_cluster.py
  bigtable/tests/unit/test_column_family.py
  bigtable/tests/unit/test_instance.py
  bigtable/tests/unit/test_row.py
  bigtable/tests/unit/test_table.py
Labels: api: bigtable, cla: yes

#5333 Fix tests after grpcio update
  api_core/google/api_core/grpc_helpers.py
  api_core/tests/unit/test_grpc_helpers.py
Labels: cla: yes

#5336 Added make_private to Storage bucket and blob
  storage/google/cloud/storage/blob.py
  storage/google/cloud/storage/bucket.py
  storage/tests/unit/test_blob.py
  storage/tests/unit/test_bucket.py
  storage/tests/unit/test_notification.py
Labels: api: storage, cla: yes, type: feature request

#5337 Release api_core 1.2.0
  api_core/CHANGELOG.md
  api_core/setup.py
Labels: cla: yes

#5342 BigQuery: fix typo in Client docstrings
  bigquery/google/cloud/bigquery/client.py
Labels: cla: yes

#5331 BigQuery: NUMERIC type support
  bigquery/google/cloud/bigquery/_helpers.py
  bigquery/google/cloud/bigquery/dbapi/_helpers.py
  bigquery/google/cloud/bigquery/dbapi/types.py
  bigquery/google/cloud/bigquery/query.py
  bigquery/google/cloud/bigquery/schema.py
  bigquery/tests/data/characters.json
  bigquery/tests/data/characters.jsonl
  bigquery/tests/data/schema.json
  bigquery/tests/system.py
  bigquery/tests/unit/test__helpers.py
  bigquery/tests/unit/test_client.py
  bigquery/tests/unit/test_dbapi__helpers.py
  bigquery/tests/unit/test_query.py
Labels: cla: yes

#5345 make dependency on logging less restrictive in error_reporting
  error_reporting/setup.py
Labels: api: error reporting, cla: no, packaging

#5346 Release storage 1.10.0
  storage/CHANGELOG.md
  storage/setup.py
Labels: cla: yes

#5343 Normalize overflow handling for max count and bytes
  pubsub/google/cloud/pubsub_v1/publisher/batch/base.py
  pubsub/google/cloud/pubsub_v1/publisher/batch/thread.py
  pubsub/google/cloud/pubsub_v1/publisher/client.py
  pubsub/tests/unit/pubsub_v1/publisher/batch/test_base.py
  pubsub/tests/unit/pubsub_v1/publisher/batch/test_thread.py
  pubsub/tests/unit/pubsub_v1/publisher/test_publisher_client.py
Labels: api: pubsub, cla: yes

#5321 Begin deprecation process for google-cloud umbrella package
  README.rst
  legacy/google-cloud/setup-README.rst
  legacy/google-cloud/setup.cfg
  legacy/google-cloud/setup.py
  nox.py
Labels: cla: yes

#5352 Tasks v2beta2
  tasks/LICENSE
  tasks/MANIFEST.in
  tasks/README.rst
  tasks/docs/conf.py
  tasks/docs/gapic/v2beta2/api.rst
  tasks/docs/gapic/v2beta2/types.rst
  tasks/docs/index.rst
  tasks/google/__init__.py
  tasks/google/cloud/__init__.py
  tasks/google/cloud/tasks.py
  tasks/google/cloud/tasks_v2beta2/__init__.py
  tasks/google/cloud/tasks_v2beta2/gapic/__init__.py
  tasks/google/cloud/tasks_v2beta2/gapic/cloud_tasks_client.py
  tasks/google/cloud/tasks_v2beta2/gapic/cloud_tasks_client_config.py
  tasks/google/cloud/tasks_v2beta2/gapic/enums.py
  tasks/google/cloud/tasks_v2beta2/proto/__init__.py
  tasks/google/cloud/tasks_v2beta2/proto/cloudtasks_pb2.py
  tasks/google/cloud/tasks_v2beta2/proto/cloudtasks_pb2_grpc.py
  tasks/google/cloud/tasks_v2beta2/proto/queue_pb2.py
  tasks/google/cloud/tasks_v2beta2/proto/queue_pb2_grpc.py
  tasks/google/cloud/tasks_v2beta2/proto/target_pb2.py
  tasks/google/cloud/tasks_v2beta2/proto/target_pb2_grpc.py
  tasks/google/cloud/tasks_v2beta2/proto/task_pb2.py
  tasks/google/cloud/tasks_v2beta2/proto/task_pb2_grpc.py
  tasks/google/cloud/tasks_v2beta2/types.py
  tasks/nox.py
  tasks/setup.cfg
  tasks/setup.py
  tasks/tests/unit/gapic/v2beta2/test_cloud_tasks_client_v2beta2.py
Labels: cla: yes

#5354 Release tasks 0.1.0
  tasks/CHANGELOG.md
  tasks/google/cloud/tasks_v2beta2/gapic/cloud_tasks_client.py
  tasks/setup.py
Labels: cla: yes

#5358 Add Redis to master README
  README.rst
Labels: cla: yes

#5363 redis: unit tests require grpcio.
  redis/setup.py
Labels: api:redis, cla: yes, packaging

#5340 BigQuery: use autosummary to split up API reference docs
  bigquery/google/cloud/bigquery/table.py
  docs/_templates/autosummary/class.rst
  docs/_templates/autosummary/module.rst
  docs/bigquery/.gitignore
  docs/bigquery/reference.rst
  docs/conf.py
  test_utils/scripts/update_docs.sh
  third_party/sphinx/LICENSE
  third_party/sphinx/README.md
  third_party/sphinx/sphinx/ext/autosummary/templates/autosummary/class.rst
  third_party/sphinx/sphinx/ext/autosummary/templates/autosummary/module.rst
Labels: cla: yes

#5364 Avoid overwriting '__module__' of messages from shared modules.
  bigquery_datatransfer/google/cloud/bigquery_datatransfer_v1/types.py
  bigtable/google/cloud/bigtable_admin_v2/types.py
  bigtable/google/cloud/bigtable_v2/types.py
  container/google/cloud/container_v1/types.py
  dataproc/google/cloud/dataproc_v1/types.py
  datastore/google/cloud/datastore_v1/types.py
  dlp/google/cloud/dlp_v2/types.py
  error_reporting/google/cloud/errorreporting_v1beta1/types.py
  firestore/google/cloud/firestore_v1beta1/types.py
  language/google/cloud/language_v1/types.py
  language/google/cloud/language_v1beta2/types.py
  logging/google/cloud/logging_v2/types.py
  monitoring/google/cloud/monitoring_v3/types.py
  oslogin/google/cloud/oslogin_v1/types.py
  pubsub/google/cloud/pubsub_v1/types.py
  redis/google/cloud/redis_v1beta1/types.py
  spanner/google/cloud/spanner_admin_database_v1/types.py
  spanner/google/cloud/spanner_admin_instance_v1/types.py
  spanner/google/cloud/spanner_v1/types.py
  speech/google/cloud/speech_v1/types.py
  speech/google/cloud/speech_v1p1beta1/types.py
  tasks/google/cloud/tasks_v2beta2/types.py
  texttospeech/google/cloud/texttospeech_v1beta1/types.py
  trace/google/cloud/trace_v1/types.py
  trace/google/cloud/trace_v2/types.py
  videointelligence/google/cloud/videointelligence_v1/types.py
  videointelligence/google/cloud/videointelligence_v1beta1/types.py
  videointelligence/google/cloud/videointelligence_v1beta2/types.py
  videointelligence/google/cloud/videointelligence_v1p1beta1/types.py
  vision/google/cloud/vision_v1/types.py
  vision/google/cloud/vision_v1p1beta1/types.py
  vision/google/cloud/vision_v1p2beta1/types.py
  websecurityscanner/google/cloud/websecurityscanner_v1alpha/types.py
Labels: api: bigquery_datatransfer, api: bigtable, api: container, api: dataproc, api: datastore, api: dlp, api: error reporting, api: firestore, api: language, api: logging, api: monitoring, api: pubsub, api: spanner, api: speech, api: text to speech, api: trace, api: video intelligence, api: vision, api:redis, cla: yes

#5365 Prune BigQuery systests identified as reduntant to snippets.
  bigquery/tests/system.py
Labels: api: bigquery, cla: yes, testing

#5366 Fixes #5353. Move manifest and include setup-readme in dist
  MANIFEST.in
  legacy/google-cloud/MANIFEST.in
  legacy/google-cloud/setup.py
Labels: cla: yes

#5355 Add v1 Endpoint for IoT
  iot/LICENSE
  iot/MANIFEST.in
  iot/README.rst
  iot/docs/conf.py
  iot/docs/gapic/v1/api.rst
  iot/docs/gapic/v1/types.rst
  iot/docs/index.rst
  iot/google/__init__.py
  iot/google/cloud/__init__.py
  iot/google/cloud/iot.py
  iot/google/cloud/iot_v1/__init__.py
  iot/google/cloud/iot_v1/gapic/__init__.py
  iot/google/cloud/iot_v1/gapic/device_manager_client.py
  iot/google/cloud/iot_v1/gapic/device_manager_client_config.py
  iot/google/cloud/iot_v1/gapic/enums.py
  iot/google/cloud/iot_v1/proto/__init__.py
  iot/google/cloud/iot_v1/proto/device_manager_pb2.py
  iot/google/cloud/iot_v1/proto/device_manager_pb2_grpc.py
  iot/google/cloud/iot_v1/proto/resources_pb2.py
  iot/google/cloud/iot_v1/proto/resources_pb2_grpc.py
  iot/google/cloud/iot_v1/types.py
  iot/nox.py
  iot/setup.cfg
  iot/setup.py
  iot/tests/system/gapic/v1/test_system_device_manager_v1.py
  iot/tests/unit/gapic/v1/test_device_manager_client_v1.py
Labels: api: iot, cla: yes

#5356 Release error_reporting 0.30.0
  error_reporting/CHANGELOG.md
  error_reporting/setup.py
Labels: api: error reporting, cla: yes, type: process

#5368 BigQuery: adds load partitioned table sample and reworks create/query samples
  docs/bigquery/snippets.py
Labels: api: bigquery, cla: yes, documentation

#5372 Make re-open failures bubble to callbacks
  pubsub/google/cloud/pubsub_v1/subscriber/_protocol/bidi.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_bidi.py
Labels: cla: yes

#5375 Fix example in subscribe's documentation
  pubsub/google/cloud/pubsub_v1/subscriber/client.py
Labels: cla: yes

#5373 Make leaser exit more quickly
  pubsub/google/cloud/pubsub_v1/subscriber/_protocol/leaser.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_leaser.py
Labels: cla: yes

#5374 Initialize references to helper threads before starting them
  pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
Labels: cla: yes

#5377 Send requests during streaming pull over a separate unary RPC
  pubsub/google/cloud/pubsub_v1/subscriber/_protocol/helper_threads.py
  pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py
Labels: cla: yes

#5378 Add link to streaming pull behavior documentation
  pubsub/google/cloud/pubsub_v1/subscriber/client.py
Labels: cla: yes

#5379 Restore the synchronous pull method
  pubsub/google/cloud/pubsub_v1/subscriber/client.py
Labels: cla: yes

#5380 Release pubsub 0.35.0
  pubsub/CHANGELOG.md
  pubsub/setup.py
Labels: cla: yes

#5383 ResourceManager: fix list_projects(filter_params)
  resource_manager/google/cloud/resource_manager/client.py
  resource_manager/tests/unit/test_client.py
Labels: cla: yes

#5385 Release 0.1.0
  iot/CHANGELOG.md
Labels: cla: yes

#5382 BigQuery: add ddl-related query stats.
  bigquery/google/cloud/bigquery/job.py
  bigquery/tests/system.py
  bigquery/tests/unit/test_job.py
Labels: cla: yes

#5075 Make client_info work without gRPC installed.
  api_core/google/api_core/gapic_v1/client_info.py
  api_core/tests/unit/gapic/test_client_info.py
Labels: api: core, cla: yes

#5386 fix trove classifier
  iot/setup.py
Labels: cla: yes

#5397 fix docstring: str -> dict
  translate/google/cloud/translate_v2/client.py
Labels: api: vision, cla: yes, documentation

#5369 BigTable: Add data app profile id
  bigtable/google/cloud/bigtable/table.py
  bigtable/tests/unit/test_table.py
Labels: cla: no

#5402 Catch errors when re-retrying send() or recv() in addition to open()
  pubsub/google/cloud/pubsub_v1/subscriber/_protocol/bidi.py
Labels: api: pubsub, cla: yes

#5401 BigQuery: Adds Python 3.7 and removes Python 3.4
  bigquery/nox.py
  bigquery/setup.py
Labels: api: bigquery, cla: yes

#5403 Attempt again to reproduce #4264.
  datastore/tests/system/test_system.py
  datastore/tests/system/utils/clear_datastore.py
  datastore/tests/system/utils/populate_datastore.py
Labels: api: datastore, cla: yes, testing

#5412 Fix retrying of bidirectional RPCs and closing the streaming pull manager
  pubsub/google/cloud/pubsub_v1/subscriber/_protocol/bidi.py
  pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py
Labels: cla: yes

#5413 Add heartbeating to the streaming pull manager
  pubsub/google/cloud/pubsub_v1/subscriber/_protocol/heartbeater.py
  pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_heartbeater.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py
Labels: cla: yes

#5414 Release pubsub 0.35.2
  pubsub/CHANGELOG.md
  pubsub/setup.py
Labels: cla: yes

#5390 BigTable: improve read rows validation performance
  bigtable/google/cloud/bigtable/row_data.py
  bigtable/tests/unit/test_row_data.py
  spanner/benchmark/bin/ycsb
Labels: api: bigtable, cla: no, performance

#5405 Add redis documentation to main index.rst
  docs/index.rst
  docs/redis
  docs/requirements.txt
  redis/docs/index.rst
  redis/google/cloud/redis_v1beta1/gapic/cloud_redis_client.py
Labels: cla: yes

#5416 Spanner: prevent process_read_batch from mutating params
  spanner/google/cloud/spanner_v1/database.py
Labels: cla: yes

#5315 BigTable: Add admin app profile methods on Instance
  bigtable/google/cloud/bigtable/instance.py
  bigtable/tests/system.py
  bigtable/tests/unit/test_instance.py
Labels: api: bigtable, cla: yes

#5418 Pass through 'session.posargs' when running Bigtable system tests.
  bigtable/nox.py
Labels: api: bigtable, cla: yes, testing

#5398 BigTable: Fixing client for system tests
  bigtable/google/cloud/bigtable/column_family.py
  bigtable/google/cloud/bigtable/instance.py
  bigtable/google/cloud/bigtable/row.py
  bigtable/google/cloud/bigtable/table.py
Labels: api: bigtable, cla: yes

#5415 BigQuery: Adds schema update options and snippets
  bigquery/google/cloud/bigquery/__init__.py
  bigquery/google/cloud/bigquery/job.py
  bigquery/tests/unit/test_job.py
  docs/bigquery/reference.rst
  docs/bigquery/snippets.py
Labels: api: bigquery, cla: yes

#5424 Add aliases for new V3 service clients.
  monitoring/google/cloud/monitoring.py
Labels: api: monitoring, cla: yes
