Repository googleapis/google-cloud-python, pull requests merged in 2018-02, with the labels that each got.

#4241 Updated CONTRIBUTING.rst to describe setting up dev environment using…
  CONTRIBUTING.rst
Labels: cla: no, documentation, type: process

#4779 Fix contrib note (based from #4241)
  CONTRIBUTING.rst
Labels: cla: yes, documentation, type: cleanup

#4860 Fix unit test for default `max_bytes` value
  pubsub/tests/unit/pubsub_v1/publisher/test_publisher_client.py
Labels: api: pubsub, cla: yes, type: cleanup

#4837 Speech v1p1beta1
  speech/google/cloud/speech_v1p1beta1/__init__.py
  speech/google/cloud/speech_v1p1beta1/gapic/__init__.py
  speech/google/cloud/speech_v1p1beta1/gapic/enums.py
  speech/google/cloud/speech_v1p1beta1/gapic/speech_client.py
  speech/google/cloud/speech_v1p1beta1/gapic/speech_client_config.py
  speech/google/cloud/speech_v1p1beta1/proto/__init__.py
  speech/google/cloud/speech_v1p1beta1/proto/cloud_speech_pb2.py
  speech/google/cloud/speech_v1p1beta1/proto/cloud_speech_pb2_grpc.py
  speech/google/cloud/speech_v1p1beta1/types.py
  speech/tests/system/gapic/v1p1beta1/test_system_speech_v1p1beta1.py
  speech/tests/unit/gapic/v1p1beta1/test_speech_client_v1p1beta1.py
Labels: api: speech, cla: yes, do not merge

#4865 Release Speech 0.32.0
  docs/speech/gapic/v1/api.rst
  docs/speech/gapic/v1/types.rst
  docs/speech/gapic/v1p1beta1/api.rst
  docs/speech/gapic/v1p1beta1/types.rst
  docs/speech/index.rst
  docs/speech/releases.rst
  speech/setup.py
Labels: automerge, cla: yes

#4863 BigQuery: Fix lint complaining
  docs/bigquery/snippets.py
Labels: api: bigquery, cla: yes, type: bug

#4875 Ignore multiple target warning in docs for now
  docs/conf.py
Labels: cla: yes

#4873 Remove gax usage from BigTable
  bigtable/google/cloud/bigtable/client.py
  bigtable/setup.py
Labels: cla: yes

#4872 Pubsub: Raise ValueError for message bytesize too big for batch
  pubsub/google/cloud/pubsub_v1/publisher/client.py
  pubsub/tests/system.py
  pubsub/tests/unit/pubsub_v1/publisher/test_publisher_client.py
Labels: api: pubsub, automerge, cla: yes, type: bug

#4762 Add max_latency to BackgroundThreadTransport
  logging/google/cloud/logging/handlers/transports/background_thread.py
  logging/tests/unit/handlers/transports/test_background_thread.py
Labels: api: logging, automerge, cla: yes, type: feature request

#4786 Allow listing/getting jobs even when there is an "invalid" job.
  bigquery/google/cloud/bigquery/job.py
  bigquery/tests/system.py
  bigquery/tests/unit/test_job.py
Labels: api: bigquery, cla: yes, priority: p1, type: bug

#4877 Regenerate gapic for datastore and remove gax.
  datastore/docs/conf.py
  datastore/docs/gapic/v1/api.rst
  datastore/docs/gapic/v1/types.rst
  datastore/docs/index.rst
  datastore/google/cloud/datastore/_gapic.py
  datastore/google/cloud/datastore/_gax.py
  datastore/google/cloud/datastore/client.py
  datastore/google/cloud/datastore_v1/__init__.py
  datastore/google/cloud/datastore_v1/gapic/datastore_client.py
  datastore/google/cloud/datastore_v1/gapic/enums.py
  datastore/google/cloud/datastore_v1/proto/datastore_pb2.py
  datastore/google/cloud/datastore_v1/proto/datastore_pb2_grpc.py
  datastore/google/cloud/datastore_v1/proto/entity_pb2.py
  datastore/google/cloud/datastore_v1/proto/query_pb2.py
  datastore/google/cloud/datastore_v1/types.py
  datastore/setup.py
  datastore/tests/unit/gapic/v1/test_datastore_client_v1.py
  datastore/tests/unit/test__gapic.py
  datastore/tests/unit/test__gax.py
  datastore/tests/unit/test_client.py
Labels: cla: yes

#4833 BigQuery: Use constant strings for job properties
  bigquery/tests/system.py
  bigquery/tests/unit/test_client.py
  bigquery/tests/unit/test_job.py
Labels: api: bigquery, cla: yes, type: cleanup

#4879 DLP
  .circleci/config.yml
  dlp/LICENSE
  dlp/MANIFEST.in
  dlp/README.rst
  dlp/docs/conf.py
  dlp/docs/gapic/v2beta1/api.rst
  dlp/docs/gapic/v2beta1/types.rst
  dlp/docs/index.rst
  dlp/google/__init__.py
  dlp/google/cloud/__init__.py
  dlp/google/cloud/dlp.py
  dlp/google/cloud/dlp_v2beta1/__init__.py
  dlp/google/cloud/dlp_v2beta1/gapic/__init__.py
  dlp/google/cloud/dlp_v2beta1/gapic/dlp_service_client.py
  dlp/google/cloud/dlp_v2beta1/gapic/dlp_service_client_config.py
  dlp/google/cloud/dlp_v2beta1/gapic/enums.py
  dlp/google/cloud/dlp_v2beta1/proto/__init__.py
  dlp/google/cloud/dlp_v2beta1/proto/dlp_pb2.py
  dlp/google/cloud/dlp_v2beta1/proto/dlp_pb2_grpc.py
  dlp/google/cloud/dlp_v2beta1/proto/storage_pb2.py
  dlp/google/cloud/dlp_v2beta1/proto/storage_pb2_grpc.py
  dlp/google/cloud/dlp_v2beta1/types.py
  dlp/nox.py
  dlp/setup.cfg
  dlp/setup.py
  dlp/tests/system/gapic/v2beta1/test_system_dlp_service_v2beta1.py
  dlp/tests/unit/gapic/v2beta1/test_dlp_service_client_v2beta1.py
  docs/dlp
  docs/index.rst
  docs/requirements.txt
Labels: automerge, cla: yes

#4884 Release DLP 0.1.0
  dlp/CHANGELOG.md
Labels: cla: yes

#4874 Support for BigQuery's NUMERIC type, which is currently in alpha.
  bigquery/google/cloud/bigquery/_helpers.py
  bigquery/google/cloud/bigquery/dbapi/_helpers.py
  bigquery/google/cloud/bigquery/dbapi/types.py
  bigquery/google/cloud/bigquery/query.py
  bigquery/google/cloud/bigquery/schema.py
  bigquery/tests/data/characters.json
  bigquery/tests/data/characters.jsonl
  bigquery/tests/data/schema.json
  bigquery/tests/system.py
  bigquery/tests/unit/test__helpers.py
  bigquery/tests/unit/test_client.py
  bigquery/tests/unit/test_dbapi__helpers.py
  bigquery/tests/unit/test_query.py
Labels: cla: no

#4883 Release datastore 1.5.0
  datastore/CHANGELOG.md
  datastore/setup.py
Labels: cla: yes

#4888 Spanner: Fix system test util to populate streaming
  spanner/tests/system/utils/populate_streaming.py
Labels: cla: yes

#4892 Add pending request backpressure for subscriber.
  pubsub/google/cloud/pubsub_v1/subscriber/_consumer.py
  pubsub/google/cloud/pubsub_v1/subscriber/policy/base.py
  pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py
  pubsub/google/cloud/pubsub_v1/types.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_consumer.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_policy_base.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_policy_thread.py
Labels: cla: yes

#4901 Release logging 1.5.0
  logging/CHANGELOG.md
  logging/setup.py
Labels: cla: yes

#4895 Add ability for subscriber to batch requests.
  pubsub/google/cloud/pubsub_v1/subscriber/_helper_threads.py
  pubsub/google/cloud/pubsub_v1/subscriber/message.py
  pubsub/google/cloud/pubsub_v1/subscriber/policy/base.py
  pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py
  pubsub/google/cloud/pubsub_v1/types.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_helper_threads.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_message.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_policy_base.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_policy_thread.py
Labels: api: pubsub, cla: yes

#4903 Release pubsub 0.31.0
  pubsub/CHANGELOG.md
  pubsub/setup.py
Labels: automerge, cla: yes

#4904 Pass '*session.posargs' through on command line for system tests.
  datastore/nox.py
Labels: api: datastore, cla: yes, testing

#4898 Fix line extension character breaking links
  docs/monitoring/usage.rst
Labels: api: monitoring, cla: yes, documentation, type: bug

#4906 Update format in `Table.full_table_id` and `TableListItem.full_table_id` docstrings.
  bigquery/google/cloud/bigquery/table.py
  bigquery/tests/unit/test_table.py
Labels: cla: yes

#4907 Removes unnecessary debug print from test
  bigquery/tests/unit/test_table.py
Labels: api: bigquery, cla: yes, type: cleanup

#4905 Exercise datastore query result paging
  datastore/tests/system/test_system.py
  datastore/tests/system/utils/clear_datastore.py
  datastore/tests/system/utils/populate_datastore.py
Labels: api: datastore, cla: yes

#4878 Add support for streaming pull receipts.
  pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py
  pubsub/tests/unit/pubsub_v1/subscriber/test_policy_thread.py
Labels: api: pubsub, cla: yes, type: feature request

#4910 [Monitoring] Convert label values to str in client.metric()
  monitoring/google/cloud/monitoring/client.py
Labels: cla: yes

#4909 Normalize all setup.py files
  api_core/setup.py
  bigquery/setup.py
  bigquery_datatransfer/setup.py
  bigtable/setup.py
  container/setup.py
  core/setup.py
  dataproc/setup.py
  datastore/setup.py
  dlp/setup.py
  dns/setup.py
  error_reporting/setup.py
  firestore/setup.py
  language/setup.py
  logging/setup.py
  monitoring/setup.py
  oslogin/setup.py
  pubsub/setup.py
  resource_manager/setup.py
  runtimeconfig/setup.py
  spanner/setup.py
  speech/setup.py
  storage/setup.py
  trace/setup.py
  translate/setup.py
  videointelligence/setup.py
  vision/setup.py
Labels: cla: yes

#4915 Don't check 'exclude_from_indexes' for empty lists.
  datastore/google/cloud/datastore/helpers.py
  datastore/tests/unit/test_helpers.py
Labels: api: datastore, cla: yes, type: bug

#4834 Multiprocessing warning in documentation
  docs/spanner/usage.rst
Labels: api: spanner, cla: yes, documentation, type: process

#4917 Release pubsub 0.32.0
  pubsub/CHANGELOG.md
Labels: cla: yes

#4922 Add ability to specify retry for `Operation` and `polling.Future`.
  api_core/google/api_core/future/polling.py
  api_core/google/api_core/operation.py
Labels: cla: yes

#4716 Do not quote embedded slashes for public / signed URLs
  storage/google/cloud/storage/blob.py
  storage/tests/system.py
  storage/tests/unit/test_blob.py
Labels: api: storage, cla: yes

#4936 Install local dependencies when running lint
  bigquery/nox.py
  bigtable/nox.py
  datastore/nox.py
  dns/nox.py
  error_reporting/nox.py
  firestore/nox.py
  language/nox.py
  logging/nox.py
  monitoring/nox.py
  pubsub/nox.py
  resource_manager/nox.py
  runtimeconfig/nox.py
  spanner/nox.py
  speech/nox.py
  storage/nox.py
  trace/nox.py
  translate/nox.py
  vision/nox.py
Labels: cla: yes

#4937 Don't run tests for every package when api_core is modified
  test_utils/scripts/get_target_packages.py
Labels: cla: yes

#4859 All non-simple field names are converted into unicode
  firestore/google/cloud/firestore_v1beta1/_helpers.py
  firestore/google/cloud/firestore_v1beta1/client.py
  firestore/tests/system.py
  firestore/tests/unit/test__helpers.py
Labels: api: firestore, automerge, cla: yes

#4734 Revert "Revert "api_core: Make PageIterator.item_to_value public. (#4702)""
  api_core/google/api_core/page_iterator.py
  api_core/tests/unit/test_page_iterator.py
  bigquery/setup.py
  bigquery/tests/unit/test_table.py
  datastore/google/cloud/datastore/query.py
  datastore/setup.py
  datastore/tests/unit/test_query.py
  spanner/google/cloud/spanner_v1/client.py
  spanner/google/cloud/spanner_v1/instance.py
  spanner/setup.py
Labels: api: core, packaging, type: process

#4916 Regenerate gapic for firestore, remove gax usage.
  firestore/docs/conf.py
  firestore/docs/gapic/v1beta1/api.rst
  firestore/docs/gapic/v1beta1/types.rst
  firestore/docs/index.rst
  firestore/google/cloud/firestore.py
  firestore/google/cloud/firestore_v1beta1/__init__.py
  firestore/google/cloud/firestore_v1beta1/_helpers.py
  firestore/google/cloud/firestore_v1beta1/batch.py
  firestore/google/cloud/firestore_v1beta1/client.py
  firestore/google/cloud/firestore_v1beta1/collection.py
  firestore/google/cloud/firestore_v1beta1/document.py
  firestore/google/cloud/firestore_v1beta1/gapic/enums.py
  firestore/google/cloud/firestore_v1beta1/gapic/firestore_admin_client.py
  firestore/google/cloud/firestore_v1beta1/gapic/firestore_admin_client_config.py
  firestore/google/cloud/firestore_v1beta1/gapic/firestore_client.py
  firestore/google/cloud/firestore_v1beta1/gapic/firestore_client_config.py
  firestore/google/cloud/firestore_v1beta1/proto/common_pb2.py
  firestore/google/cloud/firestore_v1beta1/proto/document_pb2.py
  firestore/google/cloud/firestore_v1beta1/proto/firestore_pb2.py
  firestore/google/cloud/firestore_v1beta1/proto/firestore_pb2_grpc.py
  firestore/google/cloud/firestore_v1beta1/proto/query_pb2.py
  firestore/google/cloud/firestore_v1beta1/proto/write_pb2.py
  firestore/google/cloud/firestore_v1beta1/query.py
  firestore/google/cloud/firestore_v1beta1/transaction.py
  firestore/google/cloud/firestore_v1beta1/types.py
  firestore/setup.py
  firestore/tests/system.py
  firestore/tests/unit/gapic/v1beta1/test_firestore_client_v1beta1.py
  firestore/tests/unit/test__helpers.py
  firestore/tests/unit/test_batch.py
  firestore/tests/unit/test_client.py
  firestore/tests/unit/test_collection.py
  firestore/tests/unit/test_cross_language.py
  firestore/tests/unit/test_document.py
  firestore/tests/unit/test_query.py
  firestore/tests/unit/test_transaction.py
Labels: api: firestore, cla: yes, do not merge

#4945 Release api_core 1.0.0
  api_core/CHANGELOG.md
  api_core/setup.py
Labels: cla: yes

#4757 Implement predefined acl
  storage/google/cloud/storage/acl.py
  storage/google/cloud/storage/blob.py
  storage/tests/system.py
  storage/tests/unit/test_acl.py
  storage/tests/unit/test_blob.py
Labels: api: storage, cla: yes, type: feature request

#4946 Update minimum api-core version to 1.0.0 for Datastore, BigQuery, Logging, Trace, and Spanner
  bigquery/setup.py
  datastore/setup.py
  logging/setup.py
  spanner/setup.py
  trace/setup.py
Labels: cla: yes

#4973 Release vision 0.30.1
  vision/CHANGELOG.md
  vision/setup.py
Labels: cla: yes

#4972 Release videointelligence 1.0.1
  videointelligence/CHANGELOG.md
  videointelligence/setup.py
Labels: cla: yes

#4971 Release translate 1.3.1
  translate/CHANGELOG.md
  translate/setup.py
Labels: cla: yes

#4970 Release trace 0.19.0
  trace/CHANGELOG.md
  trace/setup.py
Labels: cla: yes

#4968 Release speech 0.32.1
  speech/CHANGELOG.md
  speech/setup.py
Labels: cla: yes

#4967 Release spanner 1.1.0
  spanner/CHANGELOG.md
  spanner/setup.py
Labels: cla: yes

#4966 Release runtimeconfig 0.28.1
  runtimeconfig/CHANGELOG.md
  runtimeconfig/setup.py
Labels: cla: yes

#4965 Release resource_manager 0.28.1
  resource_manager/CHANGELOG.md
  resource_manager/setup.py
Labels: cla: yes

#4964 Release pubsub 0.32.1
  pubsub/CHANGELOG.md
  pubsub/setup.py
Labels: cla: yes

#4963 Release oslogin 0.1.1
  oslogin/CHANGELOG.md
  oslogin/setup.py
Labels: cla: yes

#4962 Release monitoring 0.28.1
  monitoring/CHANGELOG.md
  monitoring/setup.py
Labels: cla: yes

#4961 Release logging 1.6.0
  logging/CHANGELOG.md
  logging/setup.py
Labels: cla: yes

#4960 Release language 1.0.1
  language/CHANGELOG.md
  language/setup.py
Labels: cla: yes

#4959 Release firestore 0.29.0
  firestore/CHANGELOG.md
  firestore/setup.py
Labels: cla: yes

#4958 Release error_reporting 0.29.1
  error_reporting/CHANGELOG.md
  error_reporting/setup.py
Labels: cla: yes

#4957 Release dns 0.29.0
  dns/CHANGELOG.md
  dns/setup.py
Labels: cla: yes

#4956 Release dlp 0.1.1
  dlp/CHANGELOG.md
  dlp/setup.py
Labels: cla: yes

#4955 Release datastore 1.6.0
  datastore/CHANGELOG.md
  datastore/setup.py
Labels: cla: yes

#4954 Release dataproc 0.1.1
  dataproc/CHANGELOG.md
  dataproc/setup.py
Labels: cla: yes

#4952 Release container 0.1.1
  container/CHANGELOG.md
  container/setup.py
Labels: cla: yes

#4951 Release bigtable 0.29.0
  bigtable/CHANGELOG.md
  bigtable/setup.py
Labels: cla: yes

#4949 Release bigquery_datatransfer 0.1.1
  bigquery_datatransfer/CHANGELOG.md
  bigquery_datatransfer/setup.py
Labels: cla: yes

#4948 Release bigquery 0.31.0
  bigquery/CHANGELOG.md
  bigquery/setup.py
Labels: cla: yes

#4976 Allow underscores for release tags
  test_utils/scripts/circleci/get_tagged_package.py
Labels: cla: yes

#4975 Fix storage lint
  storage/tests/system.py
  storage/tests/unit/test_blob.py
Labels: cla: yes

#4969 Release storage 1.8.0
  storage/CHANGELOG.md
  storage/setup.py
Labels: cla: yes

#4977 Move request data from query string to body, allowing larger requests to work.
  translate/google/cloud/translate_v2/client.py
  translate/tests/unit/test_client.py
Labels: cla: yes

#4953 Release core 0.28.1
  core/CHANGELOG.md
  core/setup.py
Labels: cla: yes
