Repository googleapis/google-cloud-python, pull requests merged in 2018-12, with the labels that each got.

#6796 Update noxfile.
  asset/noxfile.py
Labels: cla: yes, codegen

#6818 Update noxfile.
  tasks/noxfile.py
Labels: cla: yes, codegen

#6817 Update noxfile.
  speech/noxfile.py
Labels: cla: yes, codegen

#6813 Update noxfile.
  redis/noxfile.py
Labels: cla: yes, codegen

#6812 Update noxfile.
  pubsub/noxfile.py
Labels: cla: yes, codegen

#6811 Update noxfile.
  oslogin/noxfile.py
Labels: cla: yes, codegen

#6810 Update noxfile.
  monitoring/noxfile.py
Labels: cla: yes, codegen

#6809 Update noxfile.py.
  language/noxfile.py
  language/synth.py
Labels: cla: yes, codegen

#6808 Update noxfile.
  kms/noxfile.py
Labels: cla: yes, codegen

#6807 Update noxfile.
  iot/noxfile.py
Labels: cla: yes, codegen

#6805 Update noxfile.
  error_reporting/noxfile.py
Labels: cla: yes, codegen

#6804 Update noxfile.
  dlp/noxfile.py
Labels: cla: yes, codegen

#6802 Update noxfile.
  dataproc/noxfile.py
Labels: cla: yes, codegen

#6800 Update noxfile.
  container/noxfile.py
Labels: cla: yes, codegen

#6798 Update noxfile.
  bigquery_datatransfer/noxfile.py
Labels: cla: yes, codegen

#6797 Update noxfile.
  automl/noxfile.py
Labels: cla: yes, codegen

#6821 Update noxfile.
  videointelligence/noxfile.py
Labels: cla: yes, codegen

#6819 Update noxfile.
  texttospeech/noxfile.py
Labels: cla: yes, codegen

#6816 Update noxfile.
  spanner/noxfile.py
Labels: cla: yes, codegen

#6815 Update noxfile.
  securitycenter/noxfile.py
Labels: cla: yes, codegen

#6814 Update noxfile.
  scheduler/noxfile.py
Labels: cla: yes, codegen

#6803 Update noxfile.
  datastore/noxfile.py
Labels: cla: yes, codegen

#6806 Update noxfile.
  firestore/noxfile.py
Labels: cla: yes, codegen

#6823 BigQuery: allow setting None as partition expiration
  bigquery/google/cloud/bigquery/table.py
  bigquery/tests/unit/test_table.py
Labels: api: bigquery, cla: yes, type: bug

#6827 BigQuery: add avro logical type control for load jobs.
  bigquery/google/cloud/bigquery/job.py
  bigquery/tests/unit/test_job.py
Labels: api: bigquery, cla: yes

#6769 Release api_core 1.6.0
  api_core/CHANGELOG.md
  api_core/setup.py
Labels: cla: yes

#6832 BigQuery: add avro load samples
  bigquery/docs/snippets.py
Labels: api: bigquery, cla: yes

#6741 Use moved iam.policy now at google.api_core.iam.policy
  asset/setup.py
  automl/setup.py
  bigquery/setup.py
  bigquery_storage/setup.py
  bigtable/google/cloud/bigtable/instance.py
  bigtable/google/cloud/bigtable/policy.py
  bigtable/setup.py
  container/setup.py
  dataproc/setup.py
  datastore/setup.py
  dlp/setup.py
  firestore/setup.py
  iot/setup.py
  kms/setup.py
  language/setup.py
  logging/setup.py
  monitoring/setup.py
  oslogin/setup.py
  pubsub/setup.py
  redis/setup.py
  resource_manager/setup.py
  runtimeconfig/setup.py
  scheduler/setup.py
  securitycenter/setup.py
  speech/setup.py
  storage/google/cloud/storage/blob.py
  storage/google/cloud/storage/bucket.py
  storage/setup.py
  storage/tests/unit/test_blob.py
  storage/tests/unit/test_bucket.py
  tasks/setup.py
  texttospeech/setup.py
  trace/setup.py
  translate/setup.py
  videointelligence/setup.py
  vision/setup.py
  websecurityscanner/setup.py
Labels: api: bigtable, api: storage, cla: yes, do not merge

#6694 NDB: No longer excluding `__repr__` and abstract methods in coverage.
  ndb/.coveragerc
Labels: api: ndb, cla: yes

#6775 remove iam module from core
  core/google/cloud/iam.py
  core/tests/unit/test_iam.py
  docs/core/iam.rst
Labels: cla: yes

#6834 Release core 0.29.0
  core/CHANGELOG.md
  core/setup.py
Labels: cla: yes

#6829 Firestore: for queries ordered on '__name__', expand field values to full paths.
  firestore/google/cloud/firestore_v1beta1/query.py
  firestore/tests/unit/test_query.py
Labels: api: firestore, cla: yes

#6835 Update dependency to google-cloud-core
  bigquery/setup.py
  bigtable/setup.py
  dns/setup.py
  firestore/setup.py
  logging/setup.py
  resource_manager/setup.py
  runtimeconfig/setup.py
  spanner/setup.py
  storage/setup.py
  translate/setup.py
Labels: cla: yes

#6822 Lint NDB on CI
  ndb/noxfile.py
  ndb/tests/unit/test_model.py
  ndb/tests/unit/test_query.py
  ndb/tests/unit/test_utils.py
Labels: api: ndb, cla: no

#6695 Implement comparison helpers for `ndb.Model`
  ndb/src/google/cloud/ndb/key.py
  ndb/src/google/cloud/ndb/model.py
  ndb/src/google/cloud/ndb/query.py
  ndb/tests/unit/test_model.py
Labels: api: ndb, cla: yes

#6825 Spanner: add 'operation_id' parameter 'Database.update_ddl' (#6737)
  spanner/google/cloud/spanner_v1/database.py
  spanner/tests/system/test_system.py
  spanner/tests/unit/test_database.py
Labels: api: spanner, cla: yes

#6840 Add to_bqstorage to convert from Table[Reference] google-cloud-bigquery-storage reference
  bigquery/docs/snippets.py
  bigquery/google/cloud/bigquery/table.py
  bigquery/noxfile.py
  bigquery/setup.py
  bigquery/tests/unit/test_job.py
  bigquery/tests/unit/test_table.py
Labels: api: bigquery, cla: yes

#6847 BigQuery: Fix exception type in comment
  bigquery/docs/snippets.py
Labels: cla: yes

#6841 Release container 0.2.0
  container/CHANGELOG.md
  container/setup.py
Labels: cla: yes

#6846 Spanner: blacken during codegen.
  spanner/google/cloud/spanner_v1/database.py
  spanner/tests/system/test_system.py
  spanner/tests/unit/test_database.py
Labels: api: spanner, cla: yes, codegen

#6850 Release trace 0.20.0
  trace/CHANGELOG.md
  trace/setup.py
Labels: cla: yes

#6854 Add option to use BQ Storage API with to_dataframe
  bigquery/google/cloud/bigquery/client.py
  bigquery/google/cloud/bigquery/table.py
  bigquery/tests/system.py
  bigquery/tests/unit/test_table.py
Labels: api: bigquery, api:bigquerystorage, cla: yes

#6738 Deserialize an entity from a protobuffer.
  ndb/MIGRATION_NOTES.md
  ndb/src/google/cloud/ndb/model.py
  ndb/tests/conftest.py
  ndb/tests/unit/test_model.py
Labels: api: ndb, cla: no

#6858 Update version of google-cloud-core
  datastore/setup.py
  trace/setup.py
Labels: cla: yes

#6857 Update index.rst
  speech/docs/index.rst
Labels: api: speech, cla: yes, type: docs

#6873 API Core: fix pytype build
  .gitignore
  api_core/google/api_core/iam.py
  api_core/setup.cfg
  api_core/tests/unit/test_iam.py
Labels: api: core, cla: yes, testing

#6856 Fix trace client memory leak
  trace/google/cloud/trace/client.py
  trace/google/cloud/trace/v1/client.py
  trace/tests/unit/v1/test_client_v1.py
  trace/tests/unit/v2/test_client_v2.py
Labels: api: cloudtrace, cla: yes

#6872 Videointelligence: 'synth.metadata'-only
  videointelligence/synth.metadata
Labels: api: videointelligence, cla: yes, codegen

#6871 Trace: 'synth.metadata'-only
  trace/synth.metadata
Labels: api: cloudtrace, cla: yes, codegen

#6870 Texttospeech: 'synth.metadata'-only
  texttospeech/synth.metadata
Labels: api: texttospeech, cla: yes, codegen

#6869 Tasks: 'synth.metadata'-only
  tasks/synth.metadata
Labels: api: cloudtasks, cla: yes, codegen

#6868 Speech: 'synth.metadata'-only
  speech/synth.metadata
Labels: api: speech, cla: yes, codegen

#6866 Security Center: 'synth.metadata'-only
  securitycenter/synth.metadata
Labels: api:securitycenter, cla: yes, codegen

#6865 Scheduler: 'synth.metadata'-only
  scheduler/synth.metadata
Labels: api: scheduler, cla: yes, codegen

#6863 Pubsub: 'synth.metadata'-only
  pubsub/synth.metadata
Labels: api: pubsub, cla: yes, codegen

#6862 Oslogin: 'synth.metadata'-only
  oslogin/synth.metadata
Labels: api: oslogin, cla: yes, codegen

#6864 Redis: 'synth.metadata'-only
  redis/synth.metadata
Labels: api: redis, cla: yes, codegen

#6861 Monitoring: 'synth.metadata'-only
  monitoring/synth.metadata
Labels: api: monitoring, cla: yes, codegen

#6860 Container: 'synth.metadata'-only
  container/synth.metadata
Labels: api: container, cla: yes, codegen

#6867 Spanner: 'synth.metadata'-only
  spanner/synth.metadata
Labels: api: spanner, cla: yes, codegen

#6874 DLP: pick up docstring fix via synth.
  dlp/google/cloud/dlp_v2/proto/storage_pb2.py
  dlp/synth.metadata
  dlp/synth.py
Labels: api: dlp, cla: yes, codegen

#6877 Release trace 0.20.1
  trace/CHANGELOG.md
  trace/setup.py
Labels: cla: yes

#6831 BigQuery: fix copy/paste typos in noxfile comments
  bigquery/noxfile.py
Labels: api: bigquery, cla: yes

#6855 API Core: add usage example for 'google.api_core.iam.Polcy'.
  api_core/google/api_core/iam.py
  docs/core/iam.rst
Labels: api: core, cla: yes, type: docs

#6886 Spanner: Add PingingPool to toplevel spanner module
  spanner/google/cloud/spanner.py
  spanner/google/cloud/spanner_v1/__init__.py
Labels: api: spanner, cla: yes

#6891 Release bigtable 0.32.0
  bigtable/CHANGELOG.md
  bigtable/setup.py
Labels: cla: yes

#6896 Release spanner 1.7.0
  spanner/CHANGELOG.md
  spanner/setup.py
Labels: cla: yes

#6890 Release bigquery 1.8.0
  bigquery/CHANGELOG.md
  bigquery/setup.py
Labels: cla: yes

#6889 Release datastore 1.7.2
  datastore/CHANGELOG.md
  datastore/setup.py
Labels: cla: yes

#6892 Release dns 0.29.1
  dns/CHANGELOG.md
  dns/setup.py
Labels: cla: yes

#6893 Release logging 1.9.0
  logging/CHANGELOG.md
  logging/setup.py
Labels: cla: yes

#6894 Release resource_manager 0.28.2
  resource_manager/CHANGELOG.md
  resource_manager/setup.py
Labels: cla: yes

#6904 Firestore: normalize FieldPath parsing / escaping
  firestore/docs/field_path.rst
  firestore/docs/index.rst
  firestore/google/cloud/firestore_v1beta1/_helpers.py
  firestore/google/cloud/firestore_v1beta1/client.py
  firestore/google/cloud/firestore_v1beta1/document.py
  firestore/google/cloud/firestore_v1beta1/field_path.py
  firestore/google/cloud/firestore_v1beta1/query.py
  firestore/tests/unit/test__helpers.py
  firestore/tests/unit/test_field_path.py
Labels: api: firestore, cla: yes

#6837 Firestore: impose required semantics for snapshots as cursors.
  firestore/google/cloud/firestore_v1beta1/query.py
  firestore/tests/unit/test_query.py
Labels: api: firestore, cla: yes

#6839 Firestore: add driver for query conformance tests.
  firestore/google/cloud/firestore_v1beta1/query.py
  firestore/tests/unit/test_cross_language.py
  firestore/tests/unit/test_query.py
Labels: api: firestore, cla: yes, testing

#6527 Storage: Update Blob.update_storage_class to support rewrite tokens
  storage/google/cloud/storage/blob.py
  storage/tests/system.py
  storage/tests/unit/test_blob.py
Labels: api: storage, cla: yes, performance

#6905 Add Client Library for IAM
  .kokoro/continuous/iam.cfg
  .kokoro/presubmit/iam.cfg
  .kokoro/release/iam.cfg
  docs/iam
  docs/index.rst
  docs/requirements.txt
  iam/.coveragerc
  iam/.flake8
  iam/LICENSE
  iam/MANIFEST.in
  iam/README.rst
  iam/docs/conf.py
  iam/docs/gapic/v1/api.rst
  iam/docs/gapic/v1/types.rst
  iam/docs/index.rst
  iam/google/__init__.py
  iam/google/cloud/__init__.py
  iam/google/cloud/iam_credentials.py
  iam/google/cloud/iam_credentials_v1/__init__.py
  iam/google/cloud/iam_credentials_v1/gapic/__init__.py
  iam/google/cloud/iam_credentials_v1/gapic/iam_credentials_client.py
  iam/google/cloud/iam_credentials_v1/gapic/iam_credentials_client_config.py
  iam/google/cloud/iam_credentials_v1/gapic/transports/__init__.py
  iam/google/cloud/iam_credentials_v1/gapic/transports/iam_credentials_grpc_transport.py
  iam/google/cloud/iam_credentials_v1/proto/__init__.py
  iam/google/cloud/iam_credentials_v1/proto/common_pb2.py
  iam/google/cloud/iam_credentials_v1/proto/common_pb2_grpc.py
  iam/google/cloud/iam_credentials_v1/proto/iamcredentials_pb2.py
  iam/google/cloud/iam_credentials_v1/proto/iamcredentials_pb2_grpc.py
  iam/google/cloud/iam_credentials_v1/types.py
  iam/noxfile.py
  iam/setup.cfg
  iam/setup.py
  iam/synth.metadata
  iam/synth.py
  iam/tests/unit/gapic/v1/test_iam_credentials_client_v1.py
Labels: cla: yes

#6913 fix IAM docs build
  iam/README.rst
  iam/google/cloud/iam_credentials_v1/proto/common_pb2.py
  iam/synth.metadata
  iam/synth.py
Labels: cla: yes

#6911 Release iam 0.1.0
  iam/CHANGELOG.md
Labels: api: iam, cla: yes, packaging

#6922 trove classifier fix
  iam/setup.py
Labels: cla: yes

#6923 Release iam 0.1.0
  iam/CHANGELOG.md
Labels: cla: yes

#6919 Api_core: Convert 'DatetimeWithNanos' to / from 'google.protobuf.timestamp_pb2.Timestamp'
  api_core/google/api_core/datetime_helpers.py
  api_core/tests/unit/test_datetime_helpers.py
Labels: api: core, cla: yes

#6925 Update link for Scheduler Docs
  scheduler/README.rst
Labels: api: scheduler, cla: yes, type: docs

#6853 Firestore: document timeouts for 'Query.get' / 'Collection.get'.
  firestore/google/cloud/firestore_v1beta1/collection.py
  firestore/google/cloud/firestore_v1beta1/query.py
Labels: api: firestore, cla: yes, type: docs

#6851 Remove mentions / links of 'google-cloud' from Github landing page.
  index.html
Labels: cla: yes, type: docs

#6852 Container: Improve linkage between container docs pages.
  container/README.rst
Labels: api: container, cla: yes, type: docs

#6875 Pubsub: emphasize that returned futures may differ from stdlib futures.
  pubsub/docs/publisher/index.rst
  pubsub/google/cloud/pubsub_v1/publisher/client.py
Labels: api: pubsub, cla: yes, type: docs

#6842 Docs/fixit: normalize docs for 'page_size' / 'max_results' / 'page_token'
  bigquery/google/cloud/bigquery/client.py
  bigquery/google/cloud/bigquery/table.py
  dns/google/cloud/dns/client.py
  dns/google/cloud/dns/zone.py
  firestore/google/cloud/firestore_v1beta1/document.py
  logging/google/cloud/logging/client.py
  logging/google/cloud/logging/logger.py
  monitoring/google/cloud/monitoring_v3/query.py
  resource_manager/google/cloud/resource_manager/client.py
  runtimeconfig/google/cloud/runtimeconfig/config.py
  spanner/google/cloud/spanner_v1/client.py
  spanner/google/cloud/spanner_v1/instance.py
  storage/google/cloud/storage/bucket.py
  storage/google/cloud/storage/client.py
Labels: api: bigquery, api: cloudresourcemanager, api: dns, api: firestore, api: logging, api: monitoring, api: runtimeconfig, api: spanner, api: storage, cla: yes, type: docs

#6828 Logging: allow setting name, args on default handler (post-blacken)
  logging/google/cloud/logging/client.py
  logging/google/cloud/logging/handlers/app_engine.py
  logging/google/cloud/logging/handlers/container_engine.py
  logging/google/cloud/logging/handlers/handlers.py
  logging/tests/unit/handlers/test_app_engine.py
  logging/tests/unit/handlers/test_container_engine.py
  logging/tests/unit/handlers/test_handlers.py
  logging/tests/unit/test_client.py
Labels: api: logging, cla: yes

#6884 [DNS] Ensure that `ManagedZone:exists()` does not misreport `True` result.
  dns/google/cloud/dns/zone.py
  dns/tests/unit/test_zone.py
Labels: api: dns, cla: yes

#6917 Skip signing tests for insufficient credentials
  storage/tests/system.py
Labels: cla: yes

#6928 Include grpc config in manifest
  spanner/MANIFEST.in
Labels: cla: yes

#6876 NDB: Start in on `ndb.client.Client`
  ndb/src/google/cloud/ndb/__init__.py
  ndb/src/google/cloud/ndb/client.py
  ndb/tests/conftest.py
  ndb/tests/unit/test_client.py
Labels: api: ndb, cla: yes

#6932 Storage: add missing call to batch.begin() in example.
  datastore/google/cloud/datastore/batch.py
Labels: api: datastore, cla: yes, type: docs

#6484 Bigtable: Create snippets bigtable table.py
  bigtable/docs/snippets_table.py
  bigtable/google/cloud/bigtable/table.py
  bigtable/noxfile.py
  bigtable/synth.py
Labels: api: bigtable, cla: yes

#6912 Firestore: enable use of 'WriteBatch' as a context manager.
  firestore/google/cloud/firestore_v1beta1/batch.py
  firestore/tests/unit/test_batch.py
  firestore/tests/unit/test_collection.py
  firestore/tests/unit/test_document.py
Labels: api: firestore, cla: yes

#6920 Firestore: preserve timestamp nanos in document data
  firestore/google/cloud/firestore_v1beta1/_helpers.py
  firestore/tests/unit/test__helpers.py
Labels: api: firestore, cla: yes

#6936 Release api_core 1.7.0
  api_core/CHANGELOG.md
Labels: autorelease: pending, cla: yes

#6935 Firestore: implement listen conformance
  firestore/google/cloud/firestore_v1beta1/watch.py
  firestore/tests/unit/test_cross_language.py
  firestore/tests/unit/test_watch.py
Labels: api: firestore, cla: yes, testing

#6988 Firestore: pick up stub docstring fix in GAPIC generator.
  firestore/google/cloud/firestore_v1beta1/gapic/transports/firestore_grpc_transport.py
  firestore/synth.metadata
Labels: api: firestore, cla: yes, codegen

#6916 Firestore: implement equality semantics for public types
  firestore/google/cloud/firestore_v1beta1/_helpers.py
  firestore/google/cloud/firestore_v1beta1/collection.py
  firestore/google/cloud/firestore_v1beta1/document.py
  firestore/google/cloud/firestore_v1beta1/query.py
  firestore/google/cloud/firestore_v1beta1/transforms.py
  firestore/tests/unit/test__helpers.py
  firestore/tests/unit/test_collection.py
  firestore/tests/unit/test_document.py
  firestore/tests/unit/test_query.py
  firestore/tests/unit/test_transforms.py
Labels: api: firestore, cla: yes

#6937 Firestore: pin 'google-api_core >= 1.7.0'.
  firestore/setup.py
Labels: api: firestore, cla: yes, packaging

#6941 Release automl 0.1.2
  automl/CHANGELOG.md
  automl/setup.py
Labels: autorelease: pending, cla: yes

#6940 Release asset 0.1.2
  asset/CHANGELOG.md
  asset/setup.py
Labels: autorelease: pending, cla: yes

#6944 Release bigtable 0.32.1
  bigtable/CHANGELOG.md
  bigtable/setup.py
Labels: autorelease: pending, cla: yes

#6942 Release core 0.29.1
  core/CHANGELOG.md
  core/setup.py
Labels: autorelease: pending, cla: yes

#6945 Release datastore 1.7.3
  datastore/CHANGELOG.md
  datastore/setup.py
Labels: autorelease: pending, cla: yes

#6943 Release container 0.2.1
  container/CHANGELOG.md
  container/setup.py
Labels: autorelease: pending, cla: yes

#6962 Release dataproc 0.3.0
  dataproc/CHANGELOG.md
  dataproc/setup.py
Labels: autorelease: pending, cla: yes

#6989 Release iot 0.2.0
  iot/CHANGELOG.md
  iot/setup.py
Labels: autorelease: pending, cla: yes

#6949 Release pubsub 0.39.1
  pubsub/CHANGELOG.md
  pubsub/setup.py
Labels: autorelease: pending, cla: yes

#6993 Release redis 0.2.1
  redis/CHANGELOG.md
  redis/setup.py
Labels: autorelease: pending, cla: yes

#6999 Release firestore 0.31.0
  firestore/CHANGELOG.md
  firestore/setup.py
Labels: autorelease: pending, cla: yes

#6953 Release trace 0.20.2
  trace/CHANGELOG.md
  trace/setup.py
Labels: autorelease: pending, cla: yes

#6954 Release translate 1.3.3
  translate/CHANGELOG.md
  translate/setup.py
Labels: autorelease: pending, cla: yes

#6946 Release dns 0.29.2
  dns/CHANGELOG.md
  dns/setup.py
Labels: autorelease: pending, cla: yes

#6951 Release runtimeconfig 0.28.3
  runtimeconfig/CHANGELOG.md
  runtimeconfig/setup.py
Labels: autorelease: pending, cla: yes

#6950 Release resource_manager 0.28.3
  resource_manager/CHANGELOG.md
  resource_manager/setup.py
Labels: autorelease: pending, cla: yes

#6952 Release storage 1.13.2
  storage/CHANGELOG.md
  storage/setup.py
Labels: autorelease: pending, cla: yes

#6996 Release tasks 0.4.0
  tasks/CHANGELOG.md
  tasks/setup.py
Labels: autorelease: pending, cla: yes

#6997 Release texttospeech 0.3.0
  texttospeech/CHANGELOG.md
  texttospeech/setup.py
Labels: autorelease: pending, cla: yes

#6958 Release bigquery_datatransfer 0.3.0
  bigquery_datatransfer/CHANGELOG.md
  bigquery_datatransfer/setup.py
Labels: autorelease: pending, cla: yes

#6959 Release bigquery_storage 0.1.1
  bigquery_storage/CHANGELOG.md
  bigquery_storage/setup.py
Labels: autorelease: pending, cla: no, kokoro:force-run

#6994 Release securitycenter 0.1.1
  securitycenter/CHANGELOG.md
  securitycenter/setup.py
Labels: autorelease: pending, cla: yes

#7000 Correct link to Client Library Documentation
  videointelligence/README.rst
Labels: api: videointelligence, cla: yes, type: docs

#6995 Release speech 0.36.1
  speech/CHANGELOG.md
  speech/setup.py
Labels: autorelease: pending, cla: yes

#6960 Release dlp 0.10.0
  dlp/CHANGELOG.md
  dlp/setup.py
Labels: autorelease: pending, cla: yes

#6992 Release oslogin 0.1.2
  oslogin/CHANGELOG.md
  oslogin/setup.py
Labels: autorelease: pending, cla: yes

#6955 Release videointelligence 1.6.1
  videointelligence/CHANGELOG.md
  videointelligence/setup.py
Labels: autorelease: pending, cla: yes

#6956 Release vision 0.35.2
  vision/CHANGELOG.md
  vision/setup.py
Labels: autorelease: pending, cla: yes

#6948 Release monitoring 0.31.1
  monitoring/CHANGELOG.md
  monitoring/setup.py
Labels: autorelease: pending, cla: yes

#6947 Release logging 1.9.1
  logging/CHANGELOG.md
  logging/setup.py
Labels: autorelease: pending, cla: yes, kokoro:force-run

#6998 Release websecurityscanner 0.1.1
  websecurityscanner/CHANGELOG.md
  websecurityscanner/setup.py
Labels: autorelease: pending, cla: yes

#6961 Release error_reporting 0.30.1
  error_reporting/CHANGELOG.md
  error_reporting/setup.py
Labels: autorelease: pending, cla: yes

#6991 Release language 1.1.1
  language/CHANGELOG.md
  language/setup.py
Labels: autorelease: pending, cla: yes

#6990 Release kms 0.2.1
  kms/CHANGELOG.md
  kms/setup.py
Labels: autorelease: pending, cla: yes

#7010 BigQuery: Do not return results of query magic when assigned to variable
  bigquery/google/cloud/bigquery/magics.py
  bigquery/tests/unit/test_magics.py
Labels: api: bigquery, cla: yes

#7004 Bigtable: plug systest instance leaks
  bigtable/tests/system.py
Labels: api: bigtable, cla: yes, testing

#6888 NDB: Get Datastore gRPC API stub
  ndb/src/google/cloud/ndb/_api.py
  ndb/src/google/cloud/ndb/client.py
  ndb/tests/unit/test__api.py
Labels: api: ndb, cla: yes

#7027 NDB: Implement ``Future`` base class.
  ndb/MIGRATION_NOTES.md
  ndb/src/google/cloud/ndb/tasklets.py
  ndb/tests/unit/test_tasklets.py
Labels: cla: yes
