Repository googleapis/google-cloud-python, pull requests merged in 2020-02, with the labels that each got.

#10175 refactor(bigquery): update code samples of load table file and uri
  bigquery/docs/snippets.py
  bigquery/docs/usage/encryption.rst
  bigquery/docs/usage/tables.rst
  bigquery/samples/load_table_file.py
  bigquery/samples/load_table_uri_avro.py
  bigquery/samples/load_table_uri_cmek.py
  bigquery/samples/load_table_uri_csv.py
  bigquery/samples/load_table_uri_json.py
  bigquery/samples/load_table_uri_orc.py
  bigquery/samples/load_table_uri_parquet.py
  bigquery/samples/tests/test_load_table_file.py
  bigquery/samples/tests/test_load_table_uri_avro.py
  bigquery/samples/tests/test_load_table_uri_cmek.py
  bigquery/samples/tests/test_load_table_uri_csv.py
  bigquery/samples/tests/test_load_table_uri_json.py
  bigquery/samples/tests/test_load_table_uri_orc.py
  bigquery/samples/tests/test_load_table_uri_parquet.py
Labels: api: bigquery, cla: yes

#10225 chore(bigquery): bump copyright year to 2020, tweak docstring formatting (via synth)
  bigquery/google/cloud/bigquery_v2/gapic/enums.py
  bigquery/google/cloud/bigquery_v2/proto/model_pb2.py
  bigquery/google/cloud/bigquery_v2/proto/standard_sql_pb2.py
  bigquery/google/cloud/bigquery_v2/types.py
  bigquery/synth.metadata
Labels: api: bigquery, cla: yes

#10322 chore(bigquery): release 1.24.0
  bigquery/CHANGELOG.md
  bigquery/setup.py
Labels: autorelease: pending, cla: yes

#10356 chore(recommender): use artman for generation instead of bazel
  recommender/synth.py
Labels: cla: yes

#10355 chore(asset): fix `artman_output_name`
  asset/synth.py
Labels: cla: yes
